# Site settings
title: "On Software Engineering, Mathematics<br>and Philosophy"
author: "yorick yip"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a student of Software Engineering, University of HuaZhong University of science and Techology at <a href='https://www.hust.com'>Hubei Wuhan</a>."
colophon: "This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://hugosereno.eu"

twitter_username:
github_username: babahui
linkedin_username: 
facebook_username: 
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

theme: jekyll-theme-cayman
